# Generated by Django 3.2.9 on 2021-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('date', models.CharField(max_length=80, verbose_name='date')),
                ('Category_id', models.CharField(max_length=80, verbose_name='Category_id')),
                ('Author_id', models.CharField(max_length=80, verbose_name='Author_id')),
            ],
        ),
    ]
