# Generated by Django 3.2.9 on 2022-01-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220122_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='users',
        ),
    ]
